### ISSUE TITLE
Recorded samples are pitched up 5 semitones.

### ISSUE THREAD

**Issue by bangcorrupt** [bangcorrupt/hacktribe#12]
#3 
>When loading/recording a sample, the e2 will speed up the sample. To get it back to normal, I either need to lower the speed/pitch by 20% or change the tone by -5 in the sample edit menu.

>When recording the sample and playing it back before saving it will be sped up. Once selected as an OSC in the pattern(C, Dorian scale), it will go back to the correct speed.

Possibly related to scale mode and defaulting to key of F.

**Comment by gradientledge** [comment]
thats an old school way of saving samples with less data you save it up 5 then itll be a smaller file to save more samples and you just pitch it down to use it.
