### ISSUE TITLE
When you have a stable version (aprox.) - and it's possible to upgrade after the 1st hack ?

### ISSUE THREAD

**Issue by PEPER29** [bangcorrupt/hacktribe#19]
all it' s on title ^^

**Comment by bangcorrupt** [comment]
> stable version

This will always be a hack.

**Comment by gradientledge** [comment]
so when updating do you just reflash vanilla and do the hack again was wondering this as well.

**Comment by bangcorrupt** [comment]
Apply the patch to factory sampler firmware 2.02 every time.  You can update hacktribe without flashing back to factory firmware.
