### ISSUE TITLE
MIDI Thru does not work for note messages on TRS.

### ISSUE THREAD

**Issue by bangcorrupt** [bangcorrupt/hacktribe#245]
https://github.com/bangcorrupt/hacktribe/commit/0c04b4af28f4de181067be1fb6ae3dce7daf0401#commitcomment-104529475

If MIDI is input using USB it is echoed out on both USB and TRS.

If MIDI is input using TRS, note messages are received but not echoed on either USB or TRS.

CC and program change messages are echoed correctly.

**Comment by BKLronin** [comment]
Does closed mean fixed or not possible? Ready for testing.

**Comment by bangcorrupt** [comment]
Fixed.  As far as I've tested, Thru is always on and works for USB and TRS.  Thru is not implemented for System Common and System Realtime yet, all other 2 or 3 byte MIDI 1.0 messages should be echoed correctly.

**Comment by BKLronin** [comment]
Very well! Installing... :)
