### ISSUE TITLE
Hi ! sorry for the help I ask for, it may not be your first time.

### ISSUE THREAD

**Issue by Alp136** [bangcorrupt/hacktribe#271]
Hi ! sorry for the help I ask for, it may not be your first time.

So english is not my first language, and I just absolutely don't understand what i'm doing.
I've tried to install the hacktribe editor, and the hacktribe-gui.exe, when I follow the instructions, it says "File not found: hacktribe\hash\SYSTEM.VSB.sha
Source hash file not found"

I've already downloaded the vsb from korg website, the electribe sampler 2.02 one, I don't know what I'm doing wrong.

I already tried to follow the special instruction you gave in the Q&A, but I don't understand anything, I also tried to install the dependancies, but I'm lost with all the files to download, and I don't know what to do with them..

Thanks for the help !

Also, isn't there a way to simply dowload the already hacked version of the vsb ? I don' t mean to insult anyone's work, I just don't understand why it is so hard

_Originally posted by @Alp136 in https://github.com/bangcorrupt/hacktribe/discussions/270_

**Comment by AndrewSosna** [comment]
See @bangcorrupt 's answer here for the reason: https://github.com/bangcorrupt/hacktribe/discussions/70#discussioncomment-6471355
There probably is a way to download hacked file somewhere else, but not here.
