### ISSUE TITLE
Error Invalid File

### ISSUE THREAD

**Issue by BKLronin** [bangcorrupt/hacktribe#31]
When trying to apply the software update with IFX patch. Maybe I forgot something? Header is modfied and all. Hash doesnt seem to match. 

![hash](https://user-images.githubusercontent.com/6392076/143891820-d11ca70d-1612-4b60-8d5e-0577c98fc196.PNG)

**Comment by BKLronin** [comment]
Modified Header whtich is not necessary when already patched to Sampler

**Comment by bangcorrupt** [comment]
If you have hacktribe installed you don't need to modify the header, your synth thinks it is a sampler.  

The hash will only match before modifying the header.
