### ISSUE TITLE
power consumtion 

### ISSUE THREAD

**Issue by hashtag1138** [bangcorrupt/hacktribe#318]
I've noticed that since the last update the E2 last 2h top on AA alkaline batteries.

I bough 6 brand new Ni-mh AA, I'll try again tomorrow.

Have you guys noticed that too ?

**Comment by bangcorrupt** [comment]
I haven't ever tested for power consumption. It makes sense that it would use a little more, but that seems extreme.

Are you using the `main` or `experimental` branch?  

Do you know which commit you were using before?

**Comment by bangcorrupt** [comment]
Closing as no further comment. Feel free to add more information if the issue persists.
