### ISSUE TITLE
Hello folks

### ISSUE THREAD

**Issue by maxtribe** [bangcorrupt/hacktribe#98]
Hello folks

I have another question about the new Synth Engine in the Hacktribe Firmware. I wanted to know what new possibilities you have with this one, because I'm currently looking for a way to exhaust it. Or what do you use the new synth engine for. I mainly do techno and want to make my patterns as interesting as possible. I still have the Microfreak and then the TD3, but the main device and midi clock is the Electribe. Something along those lines only in techno

Thank you for the information

Warm greetings

PS: My goal is to get a pattern like the one in the following video:

https://www.youtube.com/watch?v=bo5ZBcEGQN8&t=108s

_Originally posted by @maxtribe in https://github.com/bangcorrupt/hacktribe/discussions/94_

**Comment by bangcorrupt** [comment]
Hi, please don't repost discusions in the issue tracker.
